print ("Adolfo III Rey");
print ("Brgy Uno, Poblacion, Buenavista, Marinduque");
print ("September 13, 2002");
print ("Marinduque State College");
print ("BSIT");
print ("Second Year");
print ("Section B");
print ("Playing");
print ("Basketball");
print ("Watching movies");
print ("Listening to musics");
print ("Singing");